#!/bin/bash
set -B

tree=../../httpdocs
tmp=app/tmp/{cache/{models,persistent,views},logs,sessions,tests}

mkdir -p "$tree"
git --work-tree="$tree" checkout -f
eval mkdir -p "$tree/"
eval chmod -R 777 "$tree/$tmp"
